name: Create OnCall Report
on:
  schedule:
    # should run on mondays at 8am utc
    - cron: '45,51,57 * * * *'

jobs:
  create_issue:
    name: CreateOnCallReport
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create OnCall Report
        uses: imjohnbo/issue-bot@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ""
          labels: "Oncall-Report, actions"
          title: "[OnCall Report] START_DATE - END_DATE, MONTH, YEAR"
          body: |-
            ## Monday (PRIMARY, SECONDARY)

            ## Tuesday (PRIMARY, SECONDARY)

            ## Wednesday (PRIMARY, SECONDARY)

            ## Thursday (PRIMARY, SECONDARY)

            ## Friday (PRIMARY, SECONDARY)
          # will close previous issue with matching tags and changed the pinned report
          close-previous: true
          pinned: true
          # adds to https://github.com/Shopify/Team-Dev-Success/projects/3 in the oncall column
          project: 1
          column: Oncall Reports
