name: Create OnCall Report
on:
  schedule:
    # should run on mondays at 8am utc
    - cron: '15,21,27,33 * * * *'

jobs:
  create_issue:
    name: Create OnCall Report
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create OnCall Report
        uses: imjohnbo/issue-bot@v3.0
        with:
          labels: "Oncall Report"
          title: "[OnCall Report]"
          body: |
            ## Monday (PRIMARY, SECONDARY)

            ## Tuesday (PRIMARY, SECONDARY)

            ## Wednesday (PRIMARY, SECONDARY)

            ## Thursday (PRIMARY, SECONDARY)

            ## Friday (PRIMARY, SECONDARY)
          pinned: true
          # will close previous issue with matching tags
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
